project:
  type: website
  render:
    - "*.qmd"
  resources:
    - interactive/

website:
  title: "What is a forecast, and is it any good?"
  site-url: https://nfidd.github.io/iddconf2026/
  repo-url: https://github.com/nfidd/iddconf2026
  repo-actions: [source, issue]
  description: "A hands-on workshop on visualising, evaluating and combining infectious disease forecasts (IDDconf 2026)"
  body-footer: '<script data-goatcounter="https://nfidd.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>'
  open-graph: true
  favicon: nfidd-favicon.png
  search:
    location: navbar
    type: textbox
  navbar:
    left:
      - getting-started.qmd
      - text: "Timetable"
        href: timetable.qmd
      - sidebar:sessions
      - sidebar:reference
      - authors.qmd
    right:
      - icon: github
        href: https://github.com/nfidd/iddconf2026
  sidebar:
    - id: reference
      title: "Reference"
      style: "docked"
      contents: "reference/*.qmd"
    - id: sessions
      title: "Sessions"
      style: "docked"
      contents: "sessions/*.qmd"

execute:
  freeze: auto

format:
  html:
    theme:
      light: cosmo
      dark: solar
    css: styles.css
    link-external-icon: true
    link-external-newwindow: true
    toc: true
