---
output: github_document
---

# What is a forecast, and is it any good?

Material for the [IDDconf 2026](https://iddconf.com) workshop on visualising,
evaluating and combining infectious disease forecasts, run on the morning of
Tuesday 7 July 2026 by Kath Sherratt and Sam Abbott (LSHTM).

This is a short, forecasting-focused selection from the fuller course on
[Nowcasting and forecasting infectious disease dynamics](https://nfidd.github.io/nfidd/).
See the [workshop website](https://nfidd.github.io/iddconf2026/) for the
timetable, setup instructions, and sessions.

All the raw material is in the folder `sessions/` and is written in `quarto`.
Any changes to the quarto files are automatically updated on the web site once
committed to the `main` branch.

## Local testing

The `html` pages can be generated locally using the function

```{r render, eval = FALSE}
quarto::quarto_render()
```

## Contributors












<!-- ALL-CONTRIBUTORS-LIST:START - Do not remove or modify this section -->
<!-- prettier-ignore-start -->
<!-- markdownlint-disable -->

All contributions to this project are gratefully acknowledged using the [`allcontributors` package](https://github.com/ropensci/allcontributors) following the [all-contributors](https://allcontributors.org) specification. Contributions of any kind are welcome!

### Code


<a href="https://github.com/nfidd/nfidd/commits?author=sbfnk">sbfnk</a>, 
<a href="https://github.com/nfidd/nfidd/commits?author=seabbs">seabbs</a>, 
<a href="https://github.com/nfidd/nfidd/commits?author=kathsherratt">kathsherratt</a>, 
<a href="https://github.com/nfidd/nfidd/commits?author=dependabot[bot]">dependabot[bot]</a>, 
<a href="https://github.com/nfidd/nfidd/commits?author=github-actions[bot]">github-actions[bot]</a>, 
<a href="https://github.com/nfidd/nfidd/commits?author=jamesmbaazam">jamesmbaazam</a>, 
<a href="https://github.com/nfidd/nfidd/commits?author=ManuelStapper">ManuelStapper</a>, 
<a href="https://github.com/nfidd/nfidd/commits?author=zsusswein">zsusswein</a>



### Issues


<a href="https://github.com/nfidd/nfidd/issues?q=is%3Aissue+author%3Atoshiakiasakura">toshiakiasakura</a>, 
<a href="https://github.com/nfidd/nfidd/issues?q=is%3Aissue+author%3Ajcken95">jcken95</a>, 
<a href="https://github.com/nfidd/nfidd/issues?q=is%3Aissue+author%3ADegoot-AM">Degoot-AM</a>, 
<a href="https://github.com/nfidd/nfidd/issues?q=is%3Aissue+author%3Aepiforecasts-workflows">epiforecasts-workflows</a>


<!-- markdownlint-enable -->
<!-- prettier-ignore-end -->
<!-- ALL-CONTRIBUTORS-LIST:END -->

## License

All materials are provided under the permissive
[MIT License](https://github.com/nfidd/iddconf2026/blob/main/LICENSE).












