library("dplyr")
library("tidyr")
library("cmdstanr")
library("tidybayes")
library("purrr")
library("usethis")
library("iddconf2026")

# See data-raw/README.md for prerequisites and the regeneration order.
# Stan tooling lives in data-raw (not the installed package) as the sessions
# never fit Stan. Source it to (re)generate the forecast datasets.
source("data-raw/stan-tools.r")

# Seed the Stan sampling so regeneration is reproducible: cmdstanr draws its
# per-fit seed from R's RNG when no explicit seed is passed, so without this
# the committed forecasts could not be reproduced from source. The observed
# onsets are now loaded rather than simulated, so this seed no longer affects
# the observed data. The rw/stat/mech forecasts committed in data/ were fit
# before onsets were saved as a dataset and are left unchanged; they only need
# regenerating (with this script) if onset_df itself changes.
set.seed(12345)

# Load the saved observed onsets (generated by data-raw/generate-onsets.r) so
# the forecasts are always fit to the same realisation the sessions load with
# data(onset_df). We still build the generation time and incubation period PMFs
# here as they go into the Stan data lists below.
load("data/onset_df.rda")
gen_time_pmf <- make_gen_time_pmf()
ip_pmf <- make_ip_pmf()

# define a function to fit and forecast for a single date
make_forecast_on_day <- function(
  mod, onset_df, origin_day, horizon, gen_time_pmf, ip_pmf, data_to_list, ...
) {

  message("Fitting and forecasting for origin day: ", origin_day)

  train_df <- onset_df |>
    filter(day <= origin_day)

  data <- data_to_list(train_df, horizon, gen_time_pmf, ip_pmf)

  fit <- mod$sample(
    data = data, chains = 4, parallel_chains = 4, adapt_delta = 0.95,
    max_treedepth = 15, iter_warmup = 500, iter_sampling = 500, ...
  )

  fit |>
    gather_draws(forecast[day]) |>
    filter(!is.na(.value)) |>
    slice_head(n = 1000) |>
    mutate(horizon = day) |>
    mutate(day = day + origin_day) |>
    mutate(origin_day = origin_day) |>
    mutate(.draw = seq_len(n())) |>
    select(-.chain, -.iteration)
}

# define a forecast horizon
horizon <- 14

origin_days <- onset_df |>
  filter(day <= max(day) - horizon) |>
  filter(day > 21) |>
  pull(day)

# create forecasts every 7 days
origin_days <- origin_days[seq(1, length(origin_days), 7)]

# load the model
rw_mod <- nfidd_cmdstan_model("estimate-inf-and-r-rw-forecast")

data_to_list_rw <- function(train_df, horizon, gen_time_pmf, ip_pmf) {
  list(
    n = nrow(train_df),
    I0 = 1,
    obs = train_df$onsets,
    gen_time_max = length(gen_time_pmf),
    gen_time_pmf = gen_time_pmf,
    ip_max = length(ip_pmf) - 1,
    ip_pmf = ip_pmf,
    h = horizon
  )
}

rw_forecasts <- origin_days |>
  map_dfr(
    \(x) {
      make_forecast_on_day(
        rw_mod, onset_df, x, horizon, gen_time_pmf, ip_pmf,
        data_to_list_rw, init = \() list(init_R = 1, rw_sd = 0.01)
      )
    }
  ) |>
  mutate(model = "Random walk") |>
  ungroup()

usethis::use_data(rw_forecasts, overwrite = TRUE)

# AR model forecass
stat_mod <- nfidd_cmdstan_model("statistical-r")

stat_forecasts <- origin_days |>
  map_dfr(
    \(x) {
      make_forecast_on_day(
        stat_mod, onset_df, x, horizon, gen_time_pmf, ip_pmf, data_to_list_rw,
        init = \() list(init_R = 1, rw_sd = 0.01)
      )
    }
  ) |>
  mutate(model = "Statistical") |>
  ungroup()

usethis::use_data(stat_forecasts, overwrite = TRUE)

# Mechanistic model forecasts

mech_mod <- nfidd_cmdstan_model("mechanistic-r")

data_to_list_mech <- function(train_df, horizon, gen_time_pmf, ip_pmf) {
  data <- data_to_list_rw(train_df, horizon, gen_time_pmf, ip_pmf)
  data$N_prior <- c(10000, 2000)
  data
}

mech_forecasts <- origin_days |>
  map_dfr(
    \(x) {
      make_forecast_on_day(
        mech_mod, onset_df, x, horizon, gen_time_pmf, ip_pmf, data_to_list_mech
      )
    }
  ) |>
  mutate(model = "Mechanistic") |>
  ungroup()

usethis::use_data(mech_forecasts, overwrite = TRUE)
